source "http://rubygems.org"

# Default Rails dependencies
gem "rails", '3.1.0.rc1'
gem "sass"
gem "coffee-script"
gem "uglifier"
gem "jquery-rails"
gem "rake", "~> 0.9.1"

# Stratify-specific dependencies
gem "stratify-base"
gem "stratify-gowalla"
gem "stratify-twitter"
gem "itunes-library", :git => "git://github.com/jasonrudolph/itunes-library.git", :branch => "additional_accessors"
gem "kaminari"
gem "mongoid_rails_migrations"
gem "thoughtafter-simple-rss", :require => "simple-rss"
gem 'whenever', :require => false
gem 'capistrano' # for deployment

group "development", "test" do
  gem "factory_girl_rails", :require => nil
  gem "faker"
  gem "rspec-rails"
end

group "test" do
  gem "capybara", "~> 1.0.0.beta1"
  gem "cucumber-rails"
  gem "database_cleaner"
  gem "fakeweb"
  gem "growl" # for Guard notifications
  gem "guard-cucumber"
  gem "guard-rspec"
  gem "guard-spork"
  gem "launchy"
  gem "mocha"
  gem "rb-fsevent", :require => false if RUBY_PLATFORM =~ /darwin/i
  gem "spork"
  gem "vcr"
end
